[package]
name = "falcon512_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "falcon512_rs"
crate-type = ["cdylib", "lib"]

[dependencies]

[profile.release]
debug = true

[profile.dev]
codegen-units = 1
lto = false
opt-level = 3


[build]
rustflags = ["-C", "target-cpu=native"]

overflow_checks = false
